### ISSUE TITLE
preprocessor fails to extract filename from macro

### ISSUE THREAD

**Issue by Bertk** [wenns/sonar-cxx#500]
The following warning messages are created many times:
```
09:13:19.757 WARN  - [C:\TFS_Server\Server\boost\include\boost\mpl\aux_\include_preprocessed.hpp:37]: cannot find the sources for '#   include BOOST_PP_STRINGIZE(boost/mpl/aux_/preprocessed/AUX778076_PREPROCESSED_HEADER)'
```
The statements from boost include files are:
```c++
//c:\TFS_Server\Server\boost\include\boost\mpl\aux_\include_preprocessed.hpp


#if !defined(BOOST_NEEDS_TOKEN_PASTING_OP_FOR_TOKENS_JUXTAPOSING)
#   define AUX778076_PREPROCESSED_HEADER \
    BOOST_MPL_CFG_COMPILER_DIR/BOOST_MPL_PREPROCESSED_HEADER \
/**/
#else
#   define AUX778076_PREPROCESSED_HEADER \
    BOOST_PP_CAT(BOOST_MPL_CFG_COMPILER_DIR,/)##BOOST_MPL_PREPROCESSED_HEADER \
/**/
#endif

#if BOOST_WORKAROUND(__IBMCPP__, BOOST_TESTED_AT(700))
#   define AUX778076_INCLUDE_STRING BOOST_PP_STRINGIZE(boost/mpl/aux_/preprocessed/AUX778076_PREPROCESSED_HEADER)
#   include AUX778076_INCLUDE_STRING
#   undef AUX778076_INCLUDE_STRING
#else
#   include BOOST_PP_STRINGIZE(boost/mpl/aux_/preprocessed/AUX778076_PREPROCESSED_HEADER)
#endif


//c:\TFS_Server\Server\boost\include\boost\preprocessor\stringize.hpp
# /* BOOST_PP_STRINGIZE */
#
# if BOOST_PP_CONFIG_FLAGS() & BOOST_PP_CONFIG_MSVC()
#    define BOOST_PP_STRINGIZE(text) BOOST_PP_STRINGIZE_A((text))
#    define BOOST_PP_STRINGIZE_A(arg) BOOST_PP_STRINGIZE_I arg
# elif BOOST_PP_CONFIG_FLAGS() & BOOST_PP_CONFIG_MWCC()
#    define BOOST_PP_STRINGIZE(text) BOOST_PP_STRINGIZE_OO((text))
#    define BOOST_PP_STRINGIZE_OO(par) BOOST_PP_STRINGIZE_I ## par
# else
#    define BOOST_PP_STRINGIZE(text) BOOST_PP_STRINGIZE_I(text)
# endif
#
# define BOOST_PP_STRINGIZE_I(text) #text

```
Do you have any hints?

**Comment by guwirth** [comment]
Last release there were two fixes: see support expressions in includes (#227, #312)

**Comment by guwirth** [comment]
There is also an integration test with boost which is working:

**Scenario: Test with real boost test framework**
https://github.com/wenns/sonar-cxx/tree/master/integration-tests/testdata/boosttest_project
https://github.com/wenns/sonar-cxx/blob/master/integration-tests/features/test_execution_statistics.feature

**Comment by guwirth** [comment]
@Bertk is this still an issue?

**Comment by Bertk** [comment]
Unfortunately yes – this issue still exists. The preprocessor has some issue with the special notation used for boost preprocessed headers.

**Comment by guwirth** [comment]
Which boost version is this?

**Comment by Bertk** [comment]
We use currently boost V1.55 and VC++ V12.0.

**Comment by daniel-d** [comment]
A scan of my projects is also generating between 50 and 200 instances of this warning dependant on the project.

Boost Version: v1.58.
IDE: Microsoft Visual C 9.0 (Visual Studio 2008)
sonar-cxx-plugin version: 0.9.3-RC1

**Comment by guwirth** [comment]
@Bertk Could you break down the example above please. Remove the not used if/else/elif to see which path is active in your environment. 

Maybe something to do with #459 ? In https://github.com/wenns/sonar-cxx/blob/79894beea01bd829275c8c6e5502855bcf063cb1/cxx-squid/src/test/java/org/sonar/cxx/preprocessor/CppGrammarTest.java are already some boost tests from last fix.

**Comment by guwirth** [comment]
@Bertk Maybe solved with #459 ?

**Comment by Bertk** [comment]
The problem still exists and I suspect the following preprocessor statements 
```
#define BOOST_MPL_CFG_COMPILER_DIR plain
#define BOOST_MPL_PREPROCESSED_HEADER and.hpp
#   define AUX778076_PREPROCESSED_HEADER \
    BOOST_MPL_CFG_COMPILER_DIR/BOOST_MPL_PREPROCESSED_HEADER \
/**/
include BOOST_PP_STRINGIZE(boost/mpl/aux_/preprocessed/AUX778076_PREPROCESSED_HEADER)
```
and the resolved include statement from BOOST_PP_STRINGIZE() should be
```
#include "boost/mpl/aux_/preprocessed/plain/and.hpp"
```
The active statements from "boost\preprocessor\stringize.hpp" are
```
#    define BOOST_PP_STRINGIZE(text) BOOST_PP_STRINGIZE_A((text))
#    define BOOST_PP_STRINGIZE_A(arg) BOOST_PP_STRINGIZE_I arg
# define BOOST_PP_STRINGIZE_I(text) #text
```

**Comment by Bertk** [comment]
I think the preprocessor stringizing operation fails if multiple defines need to be managed.

(CxxPreprocessor.java line 810 – this will not resolve nested #define statements)
```
          } else {
            // otherwise the arguments have to be fully expanded before expanding the body of the macro
            newValue = serialize(expandMacro("", replacement.getValue()));
            if (i > 0 && "#".equals(body.get(i - 1).getValue())) {
              newTokens.remove(newTokens.size() - 1);
              newValue = encloseWithQuotes(quote(newValue));
            }
```
The following unit test shows the preprocessor stringizing problem
```
  @Test
  public void prescan1() {
    assert (serialize(p.parse(
          "#define str(x) #x\n"
        + "#define ITEM Hallo\n"
        + "string myItem = str(ITEM);"))
        .equals("string myItem = \"Hallo\" ; EOF"));
// FixMe Stringizing Operator
    assert (serialize(p.parse(
        "#define str(x) #x\n"
        + "#define ITEM2 Hallo\n"
        + "#define ITEM1 My\n"
        + "string myItem = str(ITEM1/ITEM2);"))
        .equals("string myItem = \"My\"/\"Hallo\" ; EOF"));
// FixMe 
// see https://msdn.microsoft.com/en-us/library/7e3a913x.aspx
    assert (serialize(p.parse(
          "#define F abc\n"
        + "#define B def\n"
        + "#define FB(arg) #arg\n"
        + "#define FB1(arg) FB(arg)\n"
        + "string myItem = FB1(F B);"))
        .equals("string myItem = \"abc\"\"def\" EOF"));
  }
```

**Comment by guwirth** [comment]
Really interesting, never know that this is working. Always thought stringizing is supporting only one parameter.
```C++
#define F abc
#define B def
#define FB(arg) #arg
#define FB1(arg) FB(arg)
void test ()
{
    FB(F B);
    FB1(F B);
    string myItem = FB1(F B);
}
```
Results in (preprocessor output of VS):
```C++
void test()
{
    "F B";
    "abc def";
    string myItem = "abc def";
}
```

**Comment by guwirth** [comment]
@Bertk Do you have the time to fix this?

**Comment by Bertk** [comment]
@guwirth Sorry but I have some other priorities and will not touch this issue for the next 2 months.

**Comment by guwirth** [comment]
Ok then I will try it.

**Comment by guwirth** [comment]
@Bertk please test #531, solves at least the stringizing problem.

**Comment by Bertk** [comment]
The solution works fine and issue can be closed after PR is merged.
